import { IPageAccueil, NewPageAccueil } from './page-accueil.model';

export const sampleWithRequiredData: IPageAccueil = {
  id: 55828,
};

export const sampleWithPartialData: IPageAccueil = {
  id: 5950,
  sec2Titre: 'Buckinghamshire',
  sec2Bouton: 'copying virtual',
  sec3Titre: 'Tonga',
  sec3Blog3SousTitre: 'Money',
  sec3Blog1Text: 'Guinée efficient pixel',
  sec3Blog3Text: 'Beauty grey',
  sec4Blog1Img: '../fake-data/blob/hipster.png',
  sec4Blog1ImgContentType: 'unknown',
  sec4Blog2SousTitre: 'strategy b Frozen',
  sec5Blog1Img: '../fake-data/blob/hipster.png',
  sec5Blog1ImgContentType: 'unknown',
  sec5Blog2Img: '../fake-data/blob/hipster.png',
  sec5Blog2ImgContentType: 'unknown',
  sec5Blog3Img: '../fake-data/blob/hipster.png',
  sec5Blog3ImgContentType: 'unknown',
  sec5Blog4Img: '../fake-data/blob/hipster.png',
  sec5Blog4ImgContentType: 'unknown',
  sec5Blog6Img: '../fake-data/blob/hipster.png',
  sec5Blog6ImgContentType: 'unknown',
  sec5Blog1SousTitre: '../fake-data/blob/hipster.png',
  sec5Blog1SousTitreContentType: 'unknown',
  sec5Blog3SousTitre: '../fake-data/blob/hipster.png',
  sec5Blog3SousTitreContentType: 'unknown',
  sec5Blog5SousTitre: '../fake-data/blob/hipster.png',
  sec5Blog5SousTitreContentType: 'unknown',
  sec5Blog6SousTitre: '../fake-data/blob/hipster.png',
  sec5Blog6SousTitreContentType: 'unknown',
  sec5Blog1Text: 'static',
  sec5Blog2Text: 'Car Rubber maximize',
  sec5Blog3Text: 'Thaïlande Frozen',
  sec5Blog4Text: 'withdrawal',
  sec5Blog5Text: 'array transmitting',
  sec5Blog6Text: 'invoice',
  sec5Blog7Text: 'motivating 24/365',
  sec6Text: 'Hat',
  sec7Titre: 'PCI Stagiaire innovative',
  sec7Img: '../fake-data/blob/hipster.png',
  sec7ImgContentType: 'unknown',
  sec9Img: '../fake-data/blob/hipster.png',
  sec9ImgContentType: 'unknown',
  sec9Text: 'Rustic Stagiaire',
};

export const sampleWithFullData: IPageAccueil = {
  id: 74777,
  sec1Titre: 'proactive Concrete system',
  sec1Texte: 'Market back',
  secImage: '../fake-data/blob/hipster.png',
  secImageContentType: 'unknown',
  sec1Bouton: 'Plastic parse Mouse',
  sec2Titre: 'synthesizing b',
  sec2Text: 'rich RAM',
  sec2Bouton: 'connect',
  sec3Titre: 'Bourgogne',
  sec3Blog1Img: '../fake-data/blob/hipster.png',
  sec3Blog1ImgContentType: 'unknown',
  sec3Blog2Img: '../fake-data/blob/hipster.png',
  sec3Blog2ImgContentType: 'unknown',
  sec3Blog3Img: '../fake-data/blob/hipster.png',
  sec3Blog3ImgContentType: 'unknown',
  sec3Blog1SousTitre: 'green purple',
  sec3Blog2SousTitre: 'Savings connect',
  sec3Blog3SousTitre: 'a',
  sec3Blog1Text: 'optimal Rubber Developpeur',
  sec3Blog2Text: 'b generate',
  sec3Blog3Text: 'Pérou COM',
  sec4Titre: 'Incredible Ergonomic transform',
  sec4Text: 'circuit bus',
  sec4Blog1Img: '../fake-data/blob/hipster.png',
  sec4Blog1ImgContentType: 'unknown',
  sec4Blog1SousTitre: 'Leone Reverse-engineered',
  sec4Blog2SousTitre: 'Liechtenstein Lorraine Keyboard',
  sec4Blog1Text: 'Chips',
  sec4Blog2Text: 'communities incentivize',
  sec5Titre: 'Trinité-et-Tobago violet open',
  sec5Blog1Img: '../fake-data/blob/hipster.png',
  sec5Blog1ImgContentType: 'unknown',
  sec5Blog2Img: '../fake-data/blob/hipster.png',
  sec5Blog2ImgContentType: 'unknown',
  sec5Blog3Img: '../fake-data/blob/hipster.png',
  sec5Blog3ImgContentType: 'unknown',
  sec5Blog4Img: '../fake-data/blob/hipster.png',
  sec5Blog4ImgContentType: 'unknown',
  sec5Blog5Img: '../fake-data/blob/hipster.png',
  sec5Blog5ImgContentType: 'unknown',
  sec5Blog6Img: '../fake-data/blob/hipster.png',
  sec5Blog6ImgContentType: 'unknown',
  sec5Blog7Img: '../fake-data/blob/hipster.png',
  sec5Blog7ImgContentType: 'unknown',
  sec5Blog1SousTitre: '../fake-data/blob/hipster.png',
  sec5Blog1SousTitreContentType: 'unknown',
  sec5Blog2SousTitre: '../fake-data/blob/hipster.png',
  sec5Blog2SousTitreContentType: 'unknown',
  sec5Blog3SousTitre: '../fake-data/blob/hipster.png',
  sec5Blog3SousTitreContentType: 'unknown',
  sec5Blog4SousTitre: '../fake-data/blob/hipster.png',
  sec5Blog4SousTitreContentType: 'unknown',
  sec5Blog5SousTitre: '../fake-data/blob/hipster.png',
  sec5Blog5SousTitreContentType: 'unknown',
  sec5Blog6SousTitre: '../fake-data/blob/hipster.png',
  sec5Blog6SousTitreContentType: 'unknown',
  sec5Blog7SousTitre: '../fake-data/blob/hipster.png',
  sec5Blog7SousTitreContentType: 'unknown',
  sec5Blog1Text: 'Australie throughput c',
  sec5Blog2Text: 'black',
  sec5Blog3Text: 'feed b Concrete',
  sec5Blog4Text: 'transmitting',
  sec5Blog5Text: 'c',
  sec5Blog6Text: 'Turquie',
  sec5Blog7Text: 'toolset',
  sec6Titre: 'feed Cambridgeshire',
  sec6Img: '../fake-data/blob/hipster.png',
  sec6ImgContentType: 'unknown',
  sec6Text: 'Computer Shilling',
  sec7Titre: 'Delesseux Keyboard Cambridgeshire',
  sec7Img: '../fake-data/blob/hipster.png',
  sec7ImgContentType: 'unknown',
  sec7Text: 'optical Practical Loan',
  sec8Titre: 'Riyal c',
  sec8Img: '../fake-data/blob/hipster.png',
  sec8ImgContentType: 'unknown',
  sec8Text: 'Wooden Refined Avon',
  sec9Titre: 'Tonga connecting relationships',
  sec9Img: '../fake-data/blob/hipster.png',
  sec9ImgContentType: 'unknown',
  sec9Text: 'Rupee',
};

export const sampleWithNewData: NewPageAccueil = {
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
